phrase:
  project_id: d22128f7781fde8cdae4bc684311c91a
  push:
    sources:
      - file: ./messages/<locale_name>.json
        params:
          file_format: nested_json
  pull:
    targets:
      - file: ./messages/<locale_name>.json
        params:
          file_format: nested_json
