---
name: "Check Kana Locales"

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "messages/ain-Latn.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - run: npm install

      - run: npx tsx ./scripts/kana.ts
        env:
          CHECK: true
